# Generated by Django 5.2 on 2025-04-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='experiencia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='formacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='habilidades',
            field=models.TextField(),
        ),
    ]
