# Generated by Django 5.2 on 2025-04-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilcandidato_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='formacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilcandidato',
            name='habilidades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
