# Generated by Django 5.2 on 2025-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilcandidato_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='formacion',
            field=models.TextField(),
        ),
    ]
