# Generated by Django 5.2 on 2025-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilcandidato_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcandidato',
            name='formacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
